name: Bug report
description: Create a report to help us improve
title: "[Bug] <Replace this part>"
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: How can we replicate this?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: What device are you using?
      options:
        - X1C
        - P1P
    validations:
      required: true
  - type: textarea
    id: diagnostic
    attributes:
      label: Diagnostic Output
      description: |
        Add your Diagnostics file download.  To get this, go to the Home Assistant Bambu Lab Integration, and click Download Diagnostics
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Log Extracts
      description: Any log information?
      render: shell
  - type: textarea
    id: other
    attributes:
      label: Other Information
      description: Anything else we should know?
